version: "2.4"
services: 
  jetbot_ros2_robot_image:
    build: 
        context: ./
        dockerfile: Dockerfile.robot
        network: host
    image: jetbot-ros2:robot
  jetbot_ros2_sim_image:
    build:
        context: ./
        dockerfile: Dockerfile.simulation
        network: host
    image: jetbot-ros2:simulation
    
  robot_app:
    container_name: robot
    image: jetbot-ros2:robot
    command: ros2 launch ${ROBOT_ROS_PKG} ${ROBOT_ROS_LAUNCH}.launch.py
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/i2c-1:/dev/ic2-1"
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket

  simulation_app:
    container_name: simulation
    image: jetbot-ros2:simulation
    command: ros2 launch ${SIM_ROS_PKG} ${SIM_ROS_LAUNCH}.launch.py
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - $HOME/.Xauthority:/root/.Xauthority
    environment:
        DISPLAY: $DISPLAY