version: "2.4"
services: 
  jetbot_ros2_robot_image:
    build: 
        context: ./
        dockerfile: Dockerfile.robot
        network: host
    image: jetbot-ros2:robot
    
  robot_app:
    container_name: robot
    image: jetbot-ros2:robot
    command: ros2 launch ${ROBOT_ROS_PKG} ${ROBOT_ROS_LAUNCH}.launch.py
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
    environment:
      - DEFAULT_SPEED=0.3